name: BrianPotts
favicon: null
layout_spectrum: 0.4368121672887355
typography_spectrum: 0.8021822818554938
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.17053280165418983
  lightness: 0.35905141942203045
  saturation: 0.7728099471423775
  rhythmicContrast: 0.41293553705327213
purpose: []
